name: 'dbt_project'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds/raw_data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    refined:
      +schema: refined_data
      +materialized: table

seeds:
  dbt_project:     
    schema: raw_data 
    raw_github_issues:
      +column_types:
        _airbyte_unique_key: text
        id: numeric
        url: text
        body: text
        user: jsonb
        draft: boolean
        state: text
        title: text
        labels: jsonb
        locked: boolean
        number: numeric
        node_id: text
        user_id: numeric
        assignee: jsonb
        comments: numeric
        html_url: text
        assignees: jsonb
        closed_at: timestamp with time zone
        milestone: jsonb
        reactions: jsonb
        created_at: timestamp with time zone
        events_url: text
        labels_url: text
        repository: text
        updated_at: timestamp with time zone
        comments_url: text
        pull_request: jsonb
        state_reason: text
        timeline_url: text
        repository_url: text
        active_lock_reason: text
        author_association: text
        performed_via_github_app: jsonb
        _airbyte_ab_id: character varying
        _airbyte_emitted_at: timestamp with time zone
        _airbyte_normalized_at: timestamp with time zone
        _airbyte_issues_hashid: text

    raw_finance_invoice:
      +column_types:
        payload: text