dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: database
      user: admin        
      password: password 
      port: 5432
      dbname: analytics_db
      schema: dev        
      threads: 4
