apiVersion: 1

datasources:
  - name: AnalyticsDB
    type: postgres
    url: database:5432                
    user: admin              
    secureJsonData:
      password: 'password'     
    jsonData:
      database: analytics_db          
      sslmode: 'disable'              
      maxOpenConns: 100               
      maxIdleConns: 100               
      maxIdleConnsAuto: true          
      connMaxLifetime: 14400          
      timescaledb: false
